fix TRACE_INCLUDE_PATH
x86_64-openwrt-linux-musl-gcc predefined "linux" as 1:
```
> echo | ./x86_64-openwrt-linux-musl-gcc -dM -E - | grep -E '^#define (linux|__linux|__linux__)'
x86_64-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
#define __linux 1
#define linux 1
#define __linux__ 1
```

include path "/openwrt/build_dir/target-x86_64_musl/linux-x86_64/i915-sriov-dkms-2026.03.05.6/drivers/gpu/drm/i915/intel_uncore_trace.h" will change to "/openwrt/build_dir/target-x86_64_musl/1-x86_64/i915-sriv-dkms-2026.03.05.6/drivers/gpu/drm/i915/intel_uncore_trace.h"
on preprocessing. (Note "/linux-x86_64/" vs "/1-x86_64/")

cause CE:
```
In file included from /openwrt/build_dir/target-x86_64_musl/linux-x86_64/i915-sriov-dkms-2026.03.05.6/drivers/gpu/drm/i915/intel_uncore_trace.h:49,
                 from /openwrt/build_dir/target-x86_64_musl/linux-x86_64/i915-sriov-dkms-2026.03.05.6/drivers/gpu/drm/i915/intel_uncore_trace.c:6:
/openwrt/build_dir/target-x86_64_musl/linux-x86_64/i915-sriov-dkms-2026.03.05.6/include/trace/define_trace.h:118:42: fatal error: /openwrt/build_dir/target-x86_64_musl/1-x86_64/i915-sriv-dkms-2026.03.05.6/drivers/gpu/drm/i915/intel_uncore_trace.h: No such file or directory
  118 | #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
      |                                          ^
compilation terminated.
```

so we use relative path to fix this issue.

Signed-off-by: Liangbin Lian <jjm2473@gmail.com>